### ISSUE TITLE
 add new user - The user role field is required

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#90] opened 2022-05-04 12:23 UTC
Cannot add new user as an error message comes up - The user role field is required

## To Reproduce
1. Go to 'People'
2. Click on 'Add new user'
3. Scroll down to 'whole page'

## Expected behavior
When your press  the user role it accepts and then you can add a new user
## Screenshots
 
![image](https://user-images.githubusercontent.com/102152014/166680390-4d1643f4-a68d-4d5a-9973-4de3a4e60354.png)

## Desktop (please complete the following information):

 - Browser [e.g. chrome]

**Comment by abumunye** [comment] 2022-05-05 09:34
Duplicate of #85

**Closed by abumunye** 2022-05-05 09:34 UTC
Labels: Bug, Cosmetic, AdminPanel
