### ISSUE TITLE
Bell always sounding when entering the app

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#150] opened 2022-07-05 08:32 UTC
## To Reproduce
1. Go to 'Order Pin pro app'
2. Click on 'the app after restarting'
3. See error

## Expected behavior
The bell only goes off when there is an order

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177285722-fcbcff2e-1fae-4418-bc91-4f0aa6dd8288.png)

## Smartphone (please complete the following information):
 - Device: [Android Tablet]

**Comment by abumunye** [comment] 2022-07-11 21:48
Duplicate of #160. Fixed for both

**Closed** 2022-08-03 09:34 UTC
Labels: Bug, Functional, Ignite360
